---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything()) 
```
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
weather_df %>% 
    mutate(text_label = str_c(
        "Location : ", name, 
        "\nprecipitation: ", prcp)) %>% 
    plot_ly(x = ~tmin, y = ~tmax, color = ~name, 
    colors = "viridis", 
    alpha = .5, text = ~text_label, 
    type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
library(forcats)
weather_df %>% 
  mutate(name = fct_reorder(name, prcp)) %>% 
  plot_ly(y = ~prcp, x = ~name, color = ~name, 
          type = "violin", colors = "viridis")
```

### Chart C

```{r}
ggp_smooth <-
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() +
  geom_smooth() + labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  ) + 
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )


ggplotly(ggp_smooth)
```

